apiVersion: apps/v1
kind: Deployment
metadata:
  name: dds-controller-manager
  namespace: composable-dra
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: dynamic-device-scaler
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: dynamic-device-scaler
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /dynamic-device-scaler
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: controller:latest
        name: dynamic-device-scaler
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
