apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dynamic-device-scaler
    app.kubernetes.io/managed-by: kustomize
  name: dds-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dds-leader-election-role
subjects:
- kind: ServiceAccount
  name: dds-controller-manager
  namespace: composable-dra
