---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests
  - composableresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests/status
  - composableresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  - resourceslices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims/status
  - resourceslices/status
  verbs:
  - get
  - patch
  - update
