apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: dynamic-device-scaler
    app.kubernetes.io/managed-by: kustomize
  name: dds-controller-manager
  namespace: composable-dra
